FROM node:18-alpine AS build

ENV REACT_APP_API_HOST=http://10.130.253.103:9801

WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --silent
COPY . .
RUN npm run build

FROM nginx:stable-alpine

# remove default files
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html

# custom nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]